#!/bin/sh
#
# release-all
#
# runs a release phase and then copies the files to be released
# over into associated places.
#
tiddlywiki \
	editions/release \
	--verbose \
	--build release \
	|| exit 1
cp -v editions/release/output/thirdflow.tid skeleton/src/tiddlers/system/plugins/TheDiveO
[ -f ../ThirdFlow.github.io/index.html ] && cp -v editions/release/output/thirdflow.* ../ThirdFlow.github.io/output
# update TW5FontAwesome project
[ -f ../TW5FontAwesome/README.md ] && cp -v editions/release/output/thirdflow.tid ../TW5FontAwesome/src/tiddlers/system/plugins/TheDiveO
# update IETF-RFC project
[ -f ../IETF-RFC/README.md ] && cp -v editions/release/output/thirdflow.tid ../IETF-RFC/src/tiddlers/system/plugins/TheDiveO
