#!/bin/sh
#
# release
# 
# generates release files:
#   editions\release\output\thirdflow.html -- the plugin demo wiki
#   editions\release\output\thirdflow.tid -- the plugin tiddler
#
tiddlywiki \
	editions/release \
	--verbose \
	--build release

